[package]
org = "ballerina"
name = "workflow_activity_tests"
version = "0.1.0"

[[dependency]]
org = "ballerina"
name = "workflow.activity"
version = "0.1.0"

[[dependency]]
org = "ballerina"
name = "workflow"
version = "0.3.0"

[build-options]
observabilityIncluded = true
